#ifndef FuzzyLog_C_bindings_h
#define FuzzyLog_C_bindings_h

/* Generated with cbindgen:0.6.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <fuzzylog.h>

typedef struct {
    uint64_t p1;
    uint64_t p2;
} WriteId;

WriteId fuzzylog_async_append(FLPtr handle,
                              const char *data,
                              uintptr_t data_size,
                              const ColorSpec *colors,
                              uintptr_t num_colors);

WriteId try_wait_for_any_append(FLPtr handle);

void wait_for_a_specific_append(FLPtr handle, WriteId write_id);

void wait_for_all_appends(FLPtr handle);

WriteId wait_for_any_append(FLPtr handle);

#endif /* FuzzyLog_C_bindings_h */
