#ifndef FuzzyLog_C_bindings_h
#define FuzzyLog_C_bindings_h

/* Generated with cbindgen:0.6.1 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

typedef struct DAG DAG;

typedef struct HashMap_order__entry HashMap_order__entry;

typedef DAG *FL_ptr;

typedef uint64_t ColorID;

typedef struct {
    uintptr_t numcolors;
    ColorID *mycolors;
} colors;

typedef HashMap_order__entry snapBody;

typedef snapBody *snapId;

void close_dag_handle(DAG *dag);

int32_t fuzzylog_append(FL_ptr handle,
                        const uint8_t *buf,
                        uintptr_t bufsize,
                        colors *nodecolors);

snapId fuzzylog_sync(FL_ptr handle,
                     void (*callback)(const uint8_t*, uintptr_t));

void fuzzylog_trim(FL_ptr handle, snapId snap);

#endif /* FuzzyLog_C_bindings_h */
